// identityCard
export const GET_ALL_IDENTITYCARDS = 'GET_ALL_IDENTITYCARDS';
export const CREATE_IDENTITYCARD = 'CREATE_IDENTITYCARD';
export const DELETE_IDENTITYCARD = 'DELETE_IDENTITYCARD';
//users
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const CREATE_USER = 'CREATE_USER';
// loadingError
export const START_REQUEST = 'START_REQUEST';
export const END_REQUEST = 'END_REQUEST';
export const ERROR_REQUEST = 'ERROR_REQUEST';

// auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
